baseurl: /NetSec/ #This is important and should be updated accordingly
destination: NetSec #default output

# Virtually all of the following options are vestigial and unused.
# The social options still work but haven't been touched since forking this.

# Site settings
title: NetSec
email: your-email@domain.com
description: "Welcome to the official CSU NetSec website. Here you will find all public resources for our group."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: github
#    url: https://github.com/

# Postal address (add as many lines as necessary)
address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# keep the following (internal jekyll config options)

# Build settings
markdown: kramdown
permalink: pretty
