url: https://tyduptyler13.github.io
baseurl: /NetSec
destination: NetSec

# Site settings
title: NetSec
email: your-email@domain.com
description: "Welcome to the official CSU NetSec website. Here you will find all public resources for our group."


# Team names, titles and social links
people:
- name: Tyler Scott
  pic: 0
  position: Full Stack Engineer
  social:
    - title: stack-overflow
      url: http://stackoverflow.com/users/986971/tyler-scott
    - title: github
      url: https://github.com/tyduptyler13
    - title: google-plus
      url: https://plus.google.com/u/0/+TylerScottMathew/posts

- name: Susmit Shannigrahi
  pic: 0
  # position: #
  # social:
  #   - title: twitter
  #     url: #
  #   - title: facebook
  #     url: #
  #   - title: linkedin
  #     url: #

- name: Anant Shah
  pic: 0

- name: Chengyu Fan
  pic: 0

- name: Daniel Rammerd
  pic: 0

- name: Dimitrios Nektarios Kounalakis
  pic: 0

- name: Ela Sienkiewicz
  pic: 0

- name: Han Zhang
  pic: 0

- name: Manaf Gharaibe
  pic: 0

- name: Spiros Thanasoulas
  pic: 0

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: github
#    url: https://github.com/

# Postal address (add as many lines as necessary)
address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
